upload_file:
  description: "Upload a file to Filen.io"
  fields:
    file_path:
      description: "Path to the file to upload"
      example: "/config/upload.txt"

download_file:
  description: "Download a file from Filen.io"
  fields:
    file_id:
      description: "ID of the file to download"
      example: "abc123xyz"
    save_path:
      description: "Local path to save the downloaded file"
      example: "/config/downloaded.txt"

create_folder:
  description: "Create a folder in Filen.io"
  fields:
    folder_name:
      description: "Name of the new folder"
      example: "My Folder"
    parent_folder_id:
      description: "Parent folder ID (optional, default: root)"
      example: "abc123"

list_folders:
  description: "List all folders in Filen.io"

delete_folder:
  description: "Delete a folder from Filen.io"
  fields:
    folder_id:
      description: "ID of the folder to delete"
      example: "xyz789"

move_file:
  description: "Move a file to a different folder"
  fields:
    file_id:
      description: "ID of the file to move"
      example: "file123"
    destination_folder_id:
      description: "ID of the folder to move the file into"
      example: "folder456"

move_folder:
  description: "Move a folder into another folder"
  fields:
    folder_id:
      description: "ID of the folder to move"
      example: "folder789"
    destination_folder_id:
      description: "ID of the destination folder"
      example: "folder456"
